// <copyright file="PostOperationcontactCreate.cs" company="">
// Copyright (c) 2018 All Rights Reserved
// </copyright>
// <author></author>
// <date>11/13/2018 11:42:05 PM</date>
// <summary>Implements the PostOperationcontactCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;

namespace CRMTraining2.Plugins
{

    /// <summary>
    /// PostOperationcontactCreate Plugin.
    /// </summary>    
    public class AddressFromPostCodePlugin: PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddressFromPostCodePlugin"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information. 
        /// When using Microsoft Dynamics 365 for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public AddressFromPostCodePlugin(string unsecure, string secure)
            : base(typeof(AddressFromPostCodePlugin))
        {
            
           // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected override void ExecuteCrmPlugin(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentException("Local contet must be given");
            }

            // Extract postcode from update message (target)
            if (localContext.PluginExecutionContext.InputParameters.Contains("Target") &&
                localContext.PluginExecutionContext.InputParameters["Target"] is Entity)
            {
                var target = (Entity) localContext.PluginExecutionContext.InputParameters["Target"];

                if (target.LogicalName == "contact" && target.Attributes.ContainsKey("address1_zipcode"))
                {
                    var postcode = target.GetAttributeValue<string>("address1_zipcode");
                    localContext.Trace($"post code found {postcode}");
                }
            }
        }
    }
}
